version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/cleaning/curse_dimensionality_sim"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

